#!/usr/bin/env bash
# A script to Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
config=\
'
backend viewholder-backend
        balance roundrobin
        server 225657-web-02 100.25.157.221:80 check
        server 225657-web-01 54.237.57.148:80 check
frontend viewholder-frontend
        bind *:80
        mode http
        default_backend viewholder-backend
'
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
