#!/usr/bin/env bash
# This script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for file in *; do
	if [ "${file:0:1}" != "." ]; then
		name=$(echo "$file" | cut -d'-' -f2-)
		echo "$name"
	fi
done
